server:
  port: 8083

spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance_service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
